namespace SmallsOnline.MsGraphClient.Models;

/// <summary>
/// The type of credential used for authentication the <see cref="GraphClient" />.
/// </summary>
public enum GraphClientCredentialType
{
    /// <summary>
    /// A secret (password) generated by Azure AD.
    /// </summary>
    Secret,
    /// <summary>
    /// A thumbprint for a certificate.
    /// </summary>
    CertificateThumbprint
}